import { ArrowDown, ArrowUp, Plus, Trash2 } from 'lucide-react'
import { Button } from '../../components/ui/button.tsx'
import { Field } from '../../components/shared.tsx'
import { FileInput, FileList } from '../activities/file-input.tsx'
import { fieldVisible, httpsUrl } from './rules.ts'
import { claimStatusLabels, templateFor, emptyEvidence, isEvidence, isIssue, isSelection, outputYearFor, type Answer, type Claim, type ClaimValues, type Evidence, type TemplateField } from './model.ts'

export function ClaimStatusBadge({ status }: { status: Claim['status'] }) {
  const tone = status === 'DRAFT' ? 'neutral' : ['REVISION_REQUIRED', 'PENDING_POLICY_REVIEW'].includes(status) ? 'warning' : ['REJECTED', 'WITHDRAWN'].includes(status) ? 'danger' : ['APPROVED', 'BATCHED'].includes(status) ? 'success' : 'info'
  return <span className={`status-badge status-${tone}`}>{claimStatusLabels[status]}</span>
}
export function AnswerView({ answer }: { answer?: Answer }) {
  if (answer === undefined || answer === '') return <span className="muted">Belum diisi</span>
  if (Array.isArray(answer)) return <ol className="claim-author-preview">{answer.map((name, index) => <li key={index}>{name || 'Belum diisi'}</li>)}</ol>
  if (isIssue(answer)) return <div className="claim-issue-view">{[['Volume', answer.volume], ['Nomor', answer.issue], ['Halaman', answer.pages], ['Tahun', answer.publicationYear]].map(([label, value]) => <span key={label}>{label}: {value || '—'}</span>)}</div>
  if (isEvidence(answer)) return <div className="claim-evidence-view">{answer.mode && <p>Jenis bukti: {answer.mode}</p>}{answer.mode === 'Hardfile' && <p>Catatan / tanda terima fisik: {answer.receipt || 'Belum tercatat'}</p>}{answer.url && (httpsUrl(answer.url) ? <a href={answer.url} target="_blank" rel="noreferrer">{answer.url}</a> : <p className="field-error">Tautan belum valid.</p>)}{answer.accessedAt && <p className="muted">Tanggal akses yang dicatat: {answer.accessedAt}</p>}{answer.verificationNote && <p>{answer.verificationNote}</p>}{answer.files.length > 0 && <FileList files={answer.files} />}{!answer.url && !answer.files.length && !answer.receipt && <span className="muted">Bukti belum dilengkapi</span>}</div>
  if (isSelection(answer)) return <p>{answer.selection || 'Belum dipilih'}{answer.selection === 'Lainnya (isi manual)' && `: ${answer.detail || 'Belum diisi'}`}</p>
  return <p className="summary-text">{answer}</p>
}
export function ClaimField({ field, value, onChange, error, onBusy }: { field: TemplateField; value?: Answer; onChange: (value: Answer) => void; error?: string; onBusy: (busy: boolean) => void }) {
  const id = `claim-field-${field.key}`, text = typeof value === 'string' ? value : '', props = { id, 'aria-invalid': !!error, 'aria-describedby': error ? `${id}-error` : field.sourceHint ? `${id}-hint` : undefined }
  let control
  if (field.control === 'ordered-repeatable-authors') {
    const authors = Array.isArray(value) ? value : []
    function move(index: number, offset: number) { const next = [...authors]; [next[index], next[index + offset]] = [next[index + offset], next[index]]; onChange(next) }
    control = <div className="claim-authors">{authors.map((name, index) => <div className="claim-author-row" key={index}><span>{index + 1}</span><input id={index === 0 ? id : `${id}-${index}`} aria-label={`Nama penulis urutan ${index + 1}`} maxLength={200} value={name} onChange={event => onChange(authors.map((current, at) => at === index ? event.target.value : current))} /><Button variant="ghost" type="button" size="icon" disabled={index === 0} aria-label={`Naikkan penulis ${index + 1}`} onClick={() => move(index, -1)}><ArrowUp size={16} /></Button><Button variant="ghost" type="button" size="icon" disabled={index === authors.length - 1} aria-label={`Turunkan penulis ${index + 1}`} onClick={() => move(index, 1)}><ArrowDown size={16} /></Button><Button variant="ghost" type="button" size="icon" aria-label={`Hapus penulis ${index + 1}`} onClick={() => onChange(authors.filter((_, at) => at !== index))}><Trash2 size={16} /></Button></div>)}<Button id={!authors.length ? id : undefined} variant="outline" type="button" disabled={authors.length >= 30} onClick={() => onChange([...authors, ''])}><Plus size={16} />Tambah Penulis</Button></div>
  } else if (field.control === 'group:volume,issue,pages,publicationYear') {
    const issue = isIssue(value) ? value : { volume: '', issue: '', pages: '', publicationYear: '' }
    control = <div className="form-grid claim-issue-grid">{(['volume', 'issue', 'pages', 'publicationYear'] as const).map((key, index) => <Field id={index === 0 ? id : `${id}-${key}`} key={key} label={{ volume: 'Volume', issue: 'Nomor', pages: 'Halaman', publicationYear: 'Tahun' }[key]}><input id={index === 0 ? id : `${id}-${key}`} type={key === 'publicationYear' ? 'number' : 'text'} maxLength={key === 'publicationYear' ? 4 : 100} value={issue[key]} onChange={event => onChange({ ...issue, [key]: event.target.value })} /></Field>)}</div>
  } else if (field.control === 'https-URL' || field.control === 'private-file-upload / URL when source permits') {
    const evidence = isEvidence(value) ? value : emptyEvidence(), privateField = field.control.startsWith('private-')
    const update = <K extends keyof Evidence>(key: K, next: Evidence[K]) => onChange({ ...evidence, [key]: next })
    control = <div className="claim-evidence-editor">{field.options && <Field id={`${id}-mode`} label="Jenis bukti"><select id={`${id}-mode`} value={evidence.mode} onChange={event => update('mode', event.target.value as Evidence['mode'])}><option value="">Pilih</option>{field.options.map(option => <option key={option}>{option}</option>)}</select></Field>}{evidence.mode === 'Hardfile' ? <Field id={id} label="Catatan penyerahan / tanda terima fisik" hint="Catatan manual ini belum merupakan konfirmasi penerimaan resmi."><textarea id={id} value={evidence.receipt} rows={3} maxLength={1000} onChange={event => update('receipt', event.target.value)} /></Field> : <><input {...props} type="url" placeholder="https://…" value={evidence.url} maxLength={2000} onChange={event => update('url', event.target.value)} /><div className="form-grid reference-metadata"><Field id={`${id}-accessed`} label="Tanggal akses (opsional)"><input id={`${id}-accessed`} type="date" value={evidence.accessedAt} onChange={event => update('accessedAt', event.target.value)} /></Field><Field id={`${id}-note`} label="Catatan rujukan (opsional)"><input id={`${id}-note`} maxLength={2000} value={evidence.verificationNote} onChange={event => update('verificationNote', event.target.value)} /></Field></div>{privateField ? <FileInput label="bukti lokal" files={evidence.files} purpose={`claim:${field.fieldId}`} onBusy={onBusy} onChange={files => update('files', files)} /> : <details className="claim-reference-snapshot"><summary>Lampiran snapshot bukti (opsional)</summary><FileInput label="snapshot bukti" files={evidence.files} purpose={`claim:${field.fieldId}`} onBusy={onBusy} onChange={files => update('files', files)} /></details>}</>}</div>
  } else if (field.control === 'select' && field.options?.includes('Lainnya (isi manual)')) {
    const selection = isSelection(value) ? value : { selection: text, detail: '' }
    control = <><select {...props} value={selection.selection} onChange={event => onChange({ ...selection, selection: event.target.value })}><option value="">Pilih</option>{field.options.map(option => <option key={option}>{option}</option>)}</select>{selection.selection === 'Lainnya (isi manual)' && <Field id={`${id}-manual`} label="Nama portal lainnya"><input id={`${id}-manual`} maxLength={500} value={selection.detail} onChange={event => onChange({ ...selection, detail: event.target.value })} /></Field>}</>
  } else if (field.control === 'select' || field.control === 'yes-no') control = <select {...props} value={text} onChange={event => onChange(event.target.value)}><option value="">Pilih</option>{field.options?.map(option => <option key={option}>{option}</option>)}</select>
  else control = <input {...props} type={['integer', 'positive-integer + verify-against-authors', 'decimal-string'].includes(field.control) ? 'number' : 'text'} min={field.control === 'decimal-string' ? 0 : 1} step={field.control === 'decimal-string' ? '0.000001' : 1} maxLength={field.key === 'work_title' ? 500 : 5000} value={text} onChange={event => onChange(event.target.value)} />
  return <div className="claim-field"><Field id={id} label={field.sourceLabel} error={error} hint={field.sourceHint ?? undefined} required={field.key === 'work_title'}>{control}</Field></div>
}
export function ClaimPreview({ values, identity, includeHidden = false }: { values: ClaimValues; identity: Claim['identity']; includeHidden?: boolean }) {
  const template = templateFor(values.categoryCode)
  return <div className="claim-preview"><p className="info-notice">Tahun luaran: {outputYearFor(values) ?? 'belum diisi'}. Identitas dan jawaban disimpan bersama pada versi pengajuan.</p>{template?.fields.filter(field => field.actor !== 'REVIEWER' && (includeHidden || fieldVisible(field, values))).map(field => <section className="claim-preview-row" key={field.fieldId}><h4>{field.sourceLabel}{!fieldVisible(field, values) && <span className="inline-demo"> · Kondisi tidak aktif; jawaban dipertahankan</span>}</h4>{field.actor === 'SYSTEM_PROFILE' ? <p>{field.key === 'applicant_name_with_title' ? identity.name : field.key === 'applicant_academic_identifier' ? identity.academicId : identity.studyProgram}</p> : <AnswerView answer={values.answers[field.key]} />}</section>)}</div>
}
