import { useState } from 'react'
import { useApp, useUser } from '../../app/context.ts'
import { Button } from '../../components/ui/button.tsx'
import { Dialog } from '../../components/ui/dialog.tsx'
import { Field } from '../../components/shared.tsx'
import { UnsavedChanges } from '../../components/unsaved-changes.tsx'
import { dateLabel, moneyLabel } from '../../lib/utils.ts'
import { policyById, quoteClaim } from '../configuration/store.ts'
import type { Claim } from './model.ts'
import { adjustClaim, administerClaim, claimDecisionAllowed, decideClaim } from './workflow.ts'

export function ClaimOperations({ claim }: { claim: Claim }) {
  const user = useUser(), { config, reloadClaims, notify } = useApp(), quote = quoteClaim(claim.values, claim.ruleVersionId), boundPolicy = policyById(claim.ruleVersionId)
  const [reviewerIds, setReviewerIds] = useState(claim.reviewerIds), [reason, setReason] = useState(''), [amount, setAmount] = useState(''), [decision, setDecision] = useState<'APPROVED' | 'REJECTED' | 'REVISION_REQUIRED'>('APPROVED'), [dirty, setDirty] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), [confirm, setConfirm] = useState<'START_CHECK' | 'ASSIGN' | 'DECIDE' | 'ADJUST' | null>(null)
  async function persist() {
    if (!confirm || busy) return
    setBusy(true); setError('')
    try { if (confirm === 'START_CHECK' || confirm === 'ASSIGN') await administerClaim(claim.id, user, claim.version, confirm, reviewerIds); else if (confirm === 'DECIDE') await decideClaim(claim.id, user, claim.version, decision, reason); else await adjustClaim(claim.id, user, claim.version, amount, reason); setDirty(false); setConfirm(null); await reloadClaims(); notify('Administrasi / keputusan klaim tersimpan pada simulasi lokal.') }
    catch (failure) { setError(failure instanceof Error ? failure.message : 'Perubahan belum tersimpan.'); setConfirm(null) } finally { setBusy(false) }
  }
  return <div className="detail-content"><h3>Administrasi, SK & Keputusan</h3><UnsavedChanges dirty={dirty} busy={busy} /><dl className="metadata-grid"><div><dt>SK terikat / pratinjau</dt><dd>{quote.policy ? `${quote.policy.reference} v${quote.policy.version}${claim.ruleVersionId ? ' · terikat' : ' · pratinjau'}` : 'Menunggu Konfigurasi SK'}</dd></div><div><dt>Tarif / quote simulasi</dt><dd>{quote.amount === null ? quote.reason : moneyLabel(quote.amount, 2)}</dd></div><div><dt>Nominal disetujui</dt><dd>{claim.approvedAmount === null ? 'Belum ada keputusan nominal' : moneyLabel(claim.approvedAmount, 2)}</dd></div><div><dt>Otoritas menurut SOP</dt><dd>{quote.policy ? quote.policy.authority === 'REVIEWER' ? 'Reviewer yang ditugaskan' : 'Ka. LPPM' : 'Menunggu SOP'}</dd></div></dl><p className="info-notice">Quote dihitung lokal berdasarkan tarif yang diinput Admin. Nilai dan hak akses harus divalidasi backend pada integrasi produksi. Batch administratif tidak menunjukkan dana telah dibayarkan.</p><fieldset className="wizard-fieldset" disabled={busy}>
      {user.role === 'OPERATOR' && <section className="form-section"><h3>Verifikasi & Penugasan</h3>{['SUBMITTED', 'PENDING_POLICY_REVIEW'].includes(claim.status) && <Button onClick={() => setConfirm('START_CHECK')}>Mulai Verifikasi Administrasi</Button>}{claim.status === 'ADMIN_CHECK' && <><p className="muted">Pilih {quote.policy?.reviewerCount ?? 'jumlah sesuai SOP'} reviewer. Penugasan membutuhkan SK/SOP terbit dan satu tarif yang sesuai.</p><div className="checklist-grid">{config.accounts.filter(account => account.active && account.role === 'REVIEWER' && account.id !== claim.ownerId).map(account => <label className="checkbox-label" key={account.id}><input type="checkbox" checked={reviewerIds.includes(account.id)} onChange={event => { setReviewerIds(ids => event.target.checked ? [...ids, account.id] : ids.filter(id => id !== account.id)); setDirty(true) }} />{account.name}</label>)}</div><Button disabled={!quote.policy || quote.amount === null} onClick={() => setConfirm('ASSIGN')}>Tugaskan Reviewer & Bekukan Quote</Button></>}</section>}
      {['LPPM', 'REVIEWER'].includes(user.role) && <section className="form-section"><h3>Keputusan Final Terpisah dari Checklist</h3><p className="muted">{claimDecisionAllowed(claim, user) ? 'Pemeriksaan versi aktif lengkap; akun ini memiliki otoritas menurut SOP.' : 'Menunggu SK/SOP terikat, semua pemeriksaan versi aktif, dan akun berwenang.'}</p><Field id="claim-decision" label="Keputusan"><select id="claim-decision" value={decision} onChange={event => { setDecision(event.target.value as typeof decision); setDirty(true) }}><option value="APPROVED">Setujui</option><option value="REJECTED">Tolak</option><option value="REVISION_REQUIRED">Minta revisi</option></select></Field><Field id="claim-decision-reason" label="Alasan keputusan" required><textarea id="claim-decision-reason" rows={3} maxLength={5000} value={reason} onChange={event => { setReason(event.target.value); setDirty(true) }} /></Field><Button disabled={!claimDecisionAllowed(claim, user) || !reason.trim()} onClick={() => setConfirm('DECIDE')}>Simpan Keputusan</Button></section>}
      {user.role === 'OPERATOR' && claim.status === 'APPROVED' && <section className="form-section"><h3>Koreksi Nominal Beralasan</h3><p className="muted">{boundPolicy?.allowAdjustment ? 'Hak koreksi Operator diaktifkan pada SOP terikat.' : 'SOP ini belum memberikan hak koreksi nominal kepada Operator.'}</p><Field id="claim-adjust-amount" label="Nominal disetujui baru (Rp)" required hint="Maksimal dua desimal; koreksi dicatat bersama nilai sebelum dan sesudah."><input id="claim-adjust-amount" inputMode="decimal" value={amount} onChange={event => { setAmount(event.target.value); setDirty(true) }} /></Field><Field id="claim-adjust-reason" label="Alasan koreksi" required><textarea id="claim-adjust-reason" rows={3} value={reason} onChange={event => { setReason(event.target.value); setDirty(true) }} /></Field><Button variant="outline" disabled={!boundPolicy?.allowAdjustment || !reason.trim()} onClick={() => setConfirm('ADJUST')}>Koreksi Nominal</Button></section>}
    </fieldset>{error && <p role="alert" className="form-error">{error}</p>}<section className="form-section"><h3>Penugasan Reviewer</h3>{claim.reviewerIds.length ? <ul>{claim.reviewerIds.map(id => <li key={id}>{config.accounts.find(account => account.id === id)?.name ?? id} · {claim.reviews.some(r => r.reviewerId === id && r.submissionVersion === claim.submissions.at(-1)?.version) ? 'Pemeriksaan versi aktif selesai' : 'Belum selesai'}</li>)}</ul> : <p className="muted">Belum ada penugasan.</p>}</section>{claim.adjustments.length > 0 && <section className="form-section"><h3>Audit Koreksi Nominal</h3>{claim.adjustments.map((entry, index) => <p key={index}>{moneyLabel(entry.before, 2)} menjadi {moneyLabel(entry.after, 2)} · {entry.reason} · {entry.actor} · {dateLabel(entry.at, true)}</p>)}</section>}{claim.batchSnapshot && <section className="form-section"><h3>Snapshot Batch Administratif</h3><p>{claim.batchSnapshot.id} · {moneyLabel(claim.batchSnapshot.amount, 2)} · {dateLabel(claim.batchSnapshot.at, true)}</p><p className="muted">Dicatat oleh {claim.batchSnapshot.actor}. Tidak ada status pembayaran.</p></section>}
    <Dialog open={!!confirm} onOpenChange={open => { if (!busy && !open) setConfirm(null) }} title="Simpan tindakan klaim?" description="Versi record, aktor, nominal, dan alasan akan dicatat pada riwayat lokal. Keputusan ini hanya simulasi."><div className="dialog-actions"><Button variant="outline" disabled={busy} onClick={() => setConfirm(null)}>Periksa kembali</Button><Button disabled={busy} onClick={persist}>Simpan Simulasi</Button></div></Dialog>
  </div>
}
