import { useMemo, useState } from 'react'
import { Link } from 'react-router'
import { useReactTable, flexRender, getCoreRowModel, getPaginationRowModel, getSortedRowModel, type ColumnDef, type SortingState } from '@tanstack/react-table'
import { ChevronLeft, ChevronRight, Download, Eye, RotateCcw, Search, ArrowUpDown } from 'lucide-react'
import { useApp, useUser } from '../../app/context.ts'
import { Field, EmptyState } from '../../components/shared.tsx'
import { Button } from '../../components/ui/button.tsx'
import { dateLabel } from '../../lib/utils.ts'
import { claimCsv, emptyClaimFilters, filterClaims } from './rules.ts'
import { claimStatuses, claimStatusLabels, templates, type Claim, type ClaimStatus } from './model.ts'
import { ClaimStatusBadge } from './fields.tsx'

export function ClaimsTable({ claims, recap = false }: { claims: Claim[]; recap?: boolean }) {
  const user = useUser(), { notify } = useApp()
  const [input, setInput] = useState(emptyClaimFilters), [filters, setFilters] = useState(emptyClaimFilters), [sorting, setSorting] = useState<SortingState>([{ id: 'date', desc: true }])
  const filtered = useMemo(() => filterClaims(claims, filters), [claims, filters]), monitor = ['OPERATOR', 'LPPM', 'ADMIN'].includes(user.role)
  const columns = useMemo<ColumnDef<Claim>[]>(() => [
    { id: 'title', accessorKey: 'title', header: 'Judul karya', cell: ({ row }) => <div className="table-title"><Link to={`/incentives/${row.original.id}`}>{row.original.title}</Link><span>{row.original.code}</span>{user.role !== 'DOSEN' && <span>{row.original.identity.name} · {row.original.identity.studyProgram}</span>}</div> },
    { id: 'category', accessorFn: claim => templates.find(template => template.code === claim.categoryCode)?.label ?? claim.categoryCode, header: 'Kategori' },
    { id: 'year', accessorKey: 'outputYear', header: 'Tahun luaran', cell: ({ row }) => row.original.outputYear ?? 'Belum diisi' },
    { id: 'date', accessorFn: claim => claim.submittedAt ?? claim.updatedAt, header: 'Tanggal', cell: ({ row }) => dateLabel(row.original.submittedAt ?? row.original.updatedAt) },
    { id: 'status', accessorFn: claim => claimStatusLabels[claim.status], header: 'Status', cell: ({ row }) => <ClaimStatusBadge status={row.original.status} /> },
    { id: 'amount', header: 'Nominal insentif', enableSorting: false, cell: () => <span className="muted">Menunggu Konfigurasi SK</span> },
    { id: 'actions', header: 'Aksi', enableSorting: false, cell: ({ row }) => <Button asChild variant="ghost" size="icon"><Link to={`/incentives/${row.original.id}`} aria-label={`Buka klaim ${row.original.title}`}><Eye size={18} /></Link></Button> },
  ], [user.role])
  const table = useReactTable({ data: filtered, columns, state: { sorting }, onSortingChange: setSorting, getCoreRowModel: getCoreRowModel(), getSortedRowModel: getSortedRowModel(), getPaginationRowModel: getPaginationRowModel(), initialState: { pagination: { pageSize: 10 } } })
  const { pageIndex, pageSize } = table.getState().pagination
  function reset() { setInput(emptyClaimFilters); setFilters(emptyClaimFilters); table.setPageIndex(0) }
  const byCategory = templates.map(template => ({ template, items: filtered.filter(claim => claim.categoryCode === template.code) })).filter(group => group.items.length)
  return <section className="surface activity-table-panel"><div className="section-heading"><div><h2>{recap ? 'Rekap Klaim Insentif' : 'Daftar Klaim Insentif'}</h2><p>{filtered.length} klaim dalam cakupan akun · data simulasi</p></div>{monitor && <Button variant="outline" disabled={!filtered.length} onClick={() => { const url = URL.createObjectURL(new Blob([claimCsv(table.getSortedRowModel().rows.map(row => row.original))], { type: 'text/csv;charset=utf-8;' })); const link = document.createElement('a'); link.href = url; link.download = 'APTIMAS-klaim-insentif-simulasi.csv'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); notify(`${filtered.length} klaim sesuai filter diekspor. Nominal tetap menunggu SK.`) }}><Download size={16} />Ekspor CSV</Button>}</div>
    <form className="table-filters filters-expanded" onSubmit={event => { event.preventDefault(); setFilters(input); table.setPageIndex(0) }}><div className="search-row"><div className="search-control"><Search size={18} /><label htmlFor="claim-search" className="sr-only">Cari judul, kode, atau pengusul</label><input id="claim-search" value={input.q} onChange={event => setInput(current => ({ ...current, q: event.target.value }))} placeholder="Cari judul, kode, atau pengusul…" /></div><Button type="submit">Cari</Button><Button type="button" variant="outline" onClick={reset}><RotateCcw size={16} />Reset</Button></div><div className="advanced-filters"><Field id="claim-category-filter" label="Kategori"><select id="claim-category-filter" value={input.category} onChange={event => setInput(current => ({ ...current, category: event.target.value }))}><option value="">Semua kategori</option>{templates.map(template => <option key={template.code} value={template.code}>{template.label}</option>)}</select></Field><Field id="claim-year-filter" label="Tahun luaran"><select id="claim-year-filter" value={input.year} onChange={event => setInput(current => ({ ...current, year: event.target.value }))}><option value="">Semua tahun</option>{[...new Set([2026, ...claims.flatMap(claim => claim.outputYear ? [claim.outputYear] : [])])].sort((a, b) => b - a).map(year => <option key={year}>{year}</option>)}</select></Field><Field id="claim-status-filter" label="Status"><select id="claim-status-filter" value={input.status} onChange={event => setInput(current => ({ ...current, status: event.target.value as ClaimStatus | '' }))}><option value="">Semua status</option>{claimStatuses.map(status => <option key={status} value={status}>{claimStatusLabels[status]}</option>)}</select></Field>{monitor && <Field id="claim-program-filter" label="Program studi"><select id="claim-program-filter" value={input.studyProgram} onChange={event => setInput(current => ({ ...current, studyProgram: event.target.value }))}><option value="">Semua prodi</option>{[...new Set(claims.map(claim => claim.identity.studyProgram))].map(program => <option key={program}>{program}</option>)}</select></Field>}</div></form>
    {recap && <div className="claim-recap"><div className="info-notice">{filtered.length} klaim sesuai filter. Total nominal: Menunggu Konfigurasi SK. Rekap ini tidak membentuk batch atau mengonfirmasi pencairan.</div><div className="table-scroll"><table><thead><tr><th>Kategori</th><th>Jumlah</th><th>Dalam review</th><th>Perlu revisi</th><th>Nominal</th></tr></thead><tbody>{byCategory.map(({ template, items }) => <tr key={template.code}><td>{template.label}</td><td>{items.length}</td><td>{items.filter(item => item.status === 'UNDER_REVIEW').length}</td><td>{items.filter(item => item.status === 'REVISION_REQUIRED').length}</td><td>Menunggu Konfigurasi SK</td></tr>)}</tbody></table></div></div>}
    <div className="table-scroll" role="region" aria-label="Tabel klaim, dapat digeser horizontal" tabIndex={0}><table><caption className="sr-only">Klaim insentif simulasi sesuai filter</caption><thead>{table.getHeaderGroups().map(group => <tr key={group.id}><th scope="col">No.</th>{group.headers.map(header => <th key={header.id} scope="col" aria-sort={header.column.getIsSorted() === 'asc' ? 'ascending' : header.column.getIsSorted() === 'desc' ? 'descending' : undefined}>{header.column.getCanSort() ? <button className="sort-button" onClick={header.column.getToggleSortingHandler()}>{flexRender(header.column.columnDef.header, header.getContext())}<ArrowUpDown size={13} /></button> : flexRender(header.column.columnDef.header, header.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map((row, index) => <tr key={row.id}><td>{pageIndex * pageSize + index + 1}</td>{row.getVisibleCells().map(cell => <td key={cell.id} className={`column-${cell.column.id}`}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>)}</tbody></table></div>
    {!filtered.length && <EmptyState title="Tidak ada klaim yang sesuai" description="Cari dengan kata lain atau reset filter. Pilih Semua tahun untuk melihat draft yang belum memiliki tahun luaran." action={<Button variant="outline" onClick={reset}>Reset filter</Button>} />}
    <div className="pagination"><label>Tampilkan<select value={pageSize} aria-label="Jumlah klaim per halaman" onChange={event => table.setPageSize(Number(event.target.value))}>{[5, 10, 20].map(size => <option key={size}>{size}</option>)}</select>per halaman</label><span className="pagination-summary" aria-live="polite">{filtered.length ? pageIndex * pageSize + 1 : 0}–{pageIndex * pageSize + table.getRowModel().rows.length} dari {filtered.length}</span><div className="pagination-buttons"><Button size="icon" variant="ghost" disabled={!table.getCanPreviousPage()} aria-label="Halaman sebelumnya" onClick={() => table.previousPage()}><ChevronLeft size={17} /></Button><span className="page-number">{pageIndex + 1}</span><Button size="icon" variant="ghost" disabled={!table.getCanNextPage()} aria-label="Halaman selanjutnya" onClick={() => table.nextPage()}><ChevronRight size={17} /></Button></div></div>
  </section>
}
