import { moneyLabel } from '../../lib/utils.ts'
import type { DraftValues } from './model.ts'
import { schemes } from './data.ts'
import { budgetCents, lineCents, keywordList, profileFor, sectionLabels } from './profiles.ts'
import { FileList } from './file-input.tsx'

export function ProposalPreview({ values, owner }: { values: DraftValues; owner: string }) {
  const p = values.proposal, profile = profileFor(values.schemeVersionId), total = budgetCents(p.budget)
  return <div className="proposal-preview"><section className="form-section"><h3>Identitas & Tim</h3><h2>{values.title || 'Judul belum diisi'}</h2><dl className="metadata-grid"><div><dt>Ketua</dt><dd>{owner}</dd></div><div><dt>Skema / tahun</dt><dd>{schemes.find(item => item.id === values.schemeVersionId)?.label ?? 'Belum dipilih'} / {values.year}</dd></div><div><dt>Rumpun / durasi</dt><dd>{p.scienceCluster || '—'} / {p.duration} bulan</dd></div><div><dt>Kata kunci</dt><dd>{keywordList(p.keywords).join(' · ') || '—'}</dd></div></dl><p className="summary-text">{values.summary || 'Ringkasan belum diisi.'}</p>{p.members.map((member, index) => <p key={index}>{member.name} · {member.academicId} · {member.affiliation} ({member.role})</p>)}{p.partners.map((partner, index) => <div key={index} className="preview-partner"><strong>{partner.name || 'Mitra belum diisi'}</strong><p>{partner.kind} · {partner.region}</p><p>{partner.address}</p><p>{partner.contact}</p>{partner.role && <p>Peran: {partner.role}</p>}{partner.resources && <p>Sumber daya / komitmen: {partner.resources}</p>}</div>)}{p.externalSystem && <p className="info-notice">Referensi manual {p.externalSystem}: {p.externalId || 'ID belum diisi'} · {p.externalStatus || 'Status belum dilaporkan'} {/^https:\/\//i.test(p.externalUrl) && <a href={p.externalUrl} target="_blank" rel="noreferrer">Buka referensi</a>} · Tidak tersinkronisasi.</p>}</section>
    <section className="form-section"><h3>Substansi</h3>{p.product.name && <div className="preview-partner"><strong>{p.product.name}</strong><p>{p.product.kind} · {p.product.sector}</p><p>{p.product.description}</p><p>Manfaat: {p.product.benefit}</p>{profile?.requireTkt && <p>TKT {p.product.tktCurrent || '—'} → {p.product.tktTarget || '—'}</p>}<p>KI: {p.product.ipStatus || 'Belum tercatat'} {p.product.ipNumber}</p></div>}{profile?.sections.map(key => <div className="preview-section" key={key}><h4>{sectionLabels[key]}</h4><p className="summary-text">{p.sections[key] || 'Belum diisi.'}</p></div>)}</section>
    <section className="form-section"><h3>Pendanaan & Jadwal</h3><div className="table-scroll"><table className="proposal-table"><thead><tr><th>Komponen / item</th><th>Volume</th><th>Harga satuan</th><th>Tahun ke-</th><th>Subtotal</th></tr></thead><tbody>{p.budget.map((item, index) => <tr key={index}><td>{item.category}<br />{item.description}</td><td>{item.quantity} {item.unit}</td><td>{moneyLabel(item.price ? Number(item.price) : null, 2)}</td><td>{item.year}</td><td>{moneyLabel(lineCents(item) === null ? null : lineCents(item)! / 100, 2)}</td></tr>)}</tbody></table></div><p className="budget-total">Total dana diajukan <strong>{moneyLabel(total === null ? null : total / 100, 2)}</strong></p><ul className="schedule-preview">{p.schedule.map((item, index) => <li key={index}><strong>{item.title}</strong><span>Tahun ke-{item.year}, bulan {item.start}–{item.end}</span></li>)}</ul></section>
    <section className="form-section"><h3>Dokumen</h3>{p.files.length ? <FileList files={p.files} /> : <p className="muted">Belum ada lampiran.</p>}</section>
    <section className="form-section"><h3>Rencana Luaran</h3><ul className="schedule-preview">{p.outputs.map((item, index) => <li key={index}><strong>{item.title}</strong><span>{item.kind} · {item.quantity} · {item.target} · {item.year}</span></li>)}</ul></section>
  </div>
}
