import { useState } from 'react'
import { useApp, useUser } from '../../app/context.ts'
import { Button } from '../../components/ui/button.tsx'
import { Dialog } from '../../components/ui/dialog.tsx'
import { Field, EmptyState } from '../../components/shared.tsx'
import { UnsavedChanges } from '../../components/unsaved-changes.tsx'
import { FileInput, FileList } from './file-input.tsx'
import { activityPolicy, activityReviewIssues, administerActivity, decideActivity, recordExternalStatus, reviewStage, saveActivityReview, stageVersion } from './workflow.ts'
import { type Activity, type ActivityReview, type LocalFile } from './model.ts'
import { dateLabel, moneyLabel } from '../../lib/utils.ts'
import { canReadActivityStage } from './rules.ts'
import { ProposalPreview } from './proposal-preview.tsx'

type Action = 'START_CHECK' | 'CORRECTION' | 'ASSIGN' | 'REVIEW_DRAFT' | 'REVIEW_FINISH' | 'APPROVE' | 'REJECT' | 'REVISION' | 'ACCEPT_MILESTONE' | 'START' | 'EXTERNAL'
const actionLabels: Record<Action, string> = { START_CHECK: 'Mulai Verifikasi Administrasi', CORRECTION: 'Minta Perbaikan Administrasi', ASSIGN: 'Tugaskan Reviewer', REVIEW_DRAFT: 'Simpan Draft Penilaian', REVIEW_FINISH: 'Selesaikan Penilaian', APPROVE: 'Setujui Proposal', REJECT: 'Tolak Proposal', REVISION: 'Minta Revisi Proposal', ACCEPT_MILESTONE: 'Terima Milestone', START: 'Mulai Pelaksanaan', EXTERNAL: 'Catat Status Eksternal' }
export function ActivityWorkflowPanel({ activity }: { activity: Activity }) {
  const user = useUser(), { config, reload, notify } = useApp(), policy = activityPolicy(activity), stage = reviewStage(activity), version = stageVersion(activity)
  const initialReview = activity.reviewDrafts.find(r => r.reviewerId === user.id && r.stage === stage && r.submissionVersion === version) ?? { reviewerId: user.id, stage, submissionVersion: version, policyId: policy?.id ?? '', scores: {}, comment: '', recommendation: '' }
  const [review, setReview] = useState<ActivityReview>(initialReview), [reviewerIds, setReviewerIds] = useState<string[]>(activity.reviewerIds), [note, setNote] = useState(''), [amount, setAmount] = useState(''), [decision, setDecision] = useState<'APPROVE' | 'REJECT' | 'REVISION'>('APPROVE'), [busy, setBusy] = useState(false), [uploading, setUploading] = useState(false), [dirty, setDirty] = useState(false), [error, setError] = useState(''), [confirm, setConfirm] = useState<Action | null>(null)
  const [external, setExternal] = useState<{ status: string; url: string; evidenceDate: string; files: LocalFile[]; funded: boolean }>({ status: '', url: '', evidenceDate: '', files: [], funded: false })
  const alreadyReviewed = activity.reviews.some(r => r.reviewerId === user.id && r.stage === stage && r.submissionVersion === version), assigned = user.role === 'REVIEWER' && activity.ownerId !== user.id && activity.reviewerIds.includes(user.id) && !alreadyReviewed && ['UNDER_REVIEW', 'PROGRESS_SUBMITTED', 'FINAL_SUBMITTED', 'OUTPUT_PENDING'].includes(activity.status)
  const complete = !!policy && activity.reviewerIds.length === policy.reviewerCount && version > 0 && activity.reviewerIds.every(id => activity.reviews.some(r => r.reviewerId === id && r.stage === stage && r.submissionVersion === version && r.policyId === policy.id))
  const canAssign = user.role === 'OPERATOR' && ['ADMIN_CHECK', 'PROGRESS_SUBMITTED', 'FINAL_SUBMITTED', 'OUTPUT_PENDING'].includes(activity.status) && !activity.reviews.some(r => r.stage === stage && r.submissionVersion === version)
  function request(action: Action) {
    setError('')
    try { if (action === 'REVIEW_FINISH') { const errors = activityReviewIssues(activity, review, user, true); if (errors.length) { setError(errors.join(' ')); return } } setConfirm(action) }
    catch (failure) { setError(failure instanceof Error ? failure.message : 'Aksi belum tersedia.') }
  }
  async function persist(action: Action) {
    if (busy || uploading) return
    setBusy(true); setError('')
    try {
      if (action === 'START_CHECK' || action === 'CORRECTION' || action === 'ASSIGN') await administerActivity(activity.id, user, activity.version, action, note, reviewerIds)
      else if (action === 'REVIEW_DRAFT' || action === 'REVIEW_FINISH') await saveActivityReview(activity.id, review, user, activity.version, action === 'REVIEW_FINISH')
      else if (action === 'EXTERNAL') await recordExternalStatus(activity.id, external, user, activity.version)
      else await decideActivity(activity.id, user, activity.version, action, note, amount)
      setDirty(false); setConfirm(null); await reload(); notify(`${actionLabels[action]} tersimpan sebagai simulasi lokal.`)
    } catch (failure) { setError(failure instanceof Error ? failure.message : 'Perubahan belum tersimpan.'); setConfirm(null) } finally { setBusy(false) }
  }
  const toggleReviewer = (id: string, checked: boolean) => { setReviewerIds(ids => checked ? [...ids, id] : ids.filter(value => value !== id)); setDirty(true) }
  return <div className="detail-content"><h3>Pemeriksaan & Keputusan Kegiatan</h3><UnsavedChanges dirty={dirty} busy={busy || uploading} /><p className="info-notice">{policy ? `${policy.reference} v${policy.version} · ${policy.reviewerCount} reviewer · keputusan Ka. LPPM. ` : 'Menunggu SOP dan rubrik terbit untuk skema ini. '}{stage} versi {version || 'belum ada'}. Pemeriksaan terikat salinan pengajuan; persetujuan bukan pencairan dana.</p>
    <section className="form-section"><h3>Dokumen Versi yang Diperiksa</h3>{!canReadActivityStage(activity, user, stage, version) ? <p className="info-notice">Versi tahap terkini tidak termasuk penugasan akun ini. Lihat versi dan riwayat pemeriksaan yang ditugaskan.</p> : stage === 'PROPOSAL' ? activity.submissions.at(-1) ? <details className="submission-version"><summary>Proposal / revisi versi {version}</summary><ProposalPreview owner={activity.ownerName} profileVersionId={activity.profileVersionId} values={activity.submissions.at(-1)!.values} /></details> : <EmptyState title="Salinan proposal belum tersedia" description="Data contoh lama hanya berisi identitas/status. Ajukan kegiatan baru atau revisi yang valid untuk mencoba pemeriksaan berbasis versi." /> : stage === 'OUTPUT' ? <>{activity.realizations.map(output => <div className="report-entry" key={output.id}><h4>{output.title}</h4><p>{output.status} · {dateLabel(output.date)}</p><FileList files={output.files} /></div>)}</> : <>{activity.reports.filter(r => r.kind === stage).slice(-1).map(report => <div className="report-entry" key={report.at}><p className="summary-text">{report.summary}</p><FileList files={report.files} /></div>)}</>}</section>
    <fieldset className="wizard-fieldset" disabled={busy || uploading}>
      {user.role === 'OPERATOR' && <section className="form-section"><h3>Administrasi & Penugasan</h3>{activity.fundingSource === 'INTERNAL' && activity.status === 'SUBMITTED' && <Button onClick={() => request('START_CHECK')}>{actionLabels.START_CHECK}</Button>}{activity.status === 'ADMIN_CHECK' && <><Field id="admin-note" label="Catatan perbaikan administrasi" hint="Wajib bila meminta perbaikan."><textarea id="admin-note" rows={3} value={note} onChange={event => { setNote(event.target.value); setDirty(true) }} /></Field><Button variant="outline" onClick={() => request('CORRECTION')}>{actionLabels.CORRECTION}</Button></>}{canAssign && <><p className="muted">Pilih {policy?.reviewerCount ?? 'jumlah sesuai SOP'} reviewer aktif. Nama pengusul dikecualikan.</p><div className="checklist-grid">{config.accounts.filter(account => account.active && account.role === 'REVIEWER' && account.id !== activity.ownerId).map(account => <label className="checkbox-label" key={account.id}><input type="checkbox" checked={reviewerIds.includes(account.id)} onChange={event => toggleReviewer(account.id, event.target.checked)} />{account.name} · {account.studyProgram}</label>)}</div><Button disabled={!policy || !version} onClick={() => request('ASSIGN')}>{actionLabels.ASSIGN}</Button></>}{activity.status === 'APPROVED' && <><Field id="start-reason" label="Catatan mulai pelaksanaan" required><textarea id="start-reason" value={note} onChange={event => { setNote(event.target.value); setDirty(true) }} /></Field><Button disabled={!policy} onClick={() => request('START')}>{actionLabels.START}</Button></>}{activity.fundingSource !== 'INTERNAL' && ['SUBMITTED', 'EXTERNAL_TRACKING'].includes(activity.status) && <><h4>Hasil Eksternal yang Dilaporkan</h4><p className="info-notice">Dicatat oleh Operator sebagai EXTERNAL_MANUAL, tanpa sinkronisasi portal. Bukti keputusan wajib disertakan.</p><div className="form-grid">{(['status', 'url', 'evidenceDate'] as const).map(key => <Field key={key} id={`external-${key}`} label={{ status: 'Status resmi yang dilaporkan', url: 'Tautan sumber HTTPS', evidenceDate: 'Tanggal dokumen sumber' }[key]} required={key !== 'url'}><input id={`external-${key}`} type={key === 'evidenceDate' ? 'date' : 'text'} value={external[key]} onChange={event => { setExternal(current => ({ ...current, [key]: event.target.value })); setDirty(true) }} /></Field>)}</div><FileInput files={external.files} purpose="external" label="dokumen keputusan eksternal" onBusy={setUploading} onChange={files => { setExternal(current => ({ ...current, files })); setDirty(true) }} /><label className="checkbox-label"><input type="checkbox" checked={external.funded} onChange={event => { setExternal(current => ({ ...current, funded: event.target.checked })); setDirty(true) }} />Bukti menyatakan hibah diterima; buka pelaksanaan menurut SOP milestone</label><Button onClick={() => request('EXTERNAL')}>{actionLabels.EXTERNAL}</Button></>}</section>}
      {assigned && <section className="form-section"><h3>Penilaian Reviewer</h3>{policy && version ? <form onSubmit={event => { event.preventDefault(); request('REVIEW_FINISH') }}><div className="rubric-fields">{policy.rubric.map(rubric => <Field key={rubric.id} id={`score-${rubric.id}`} label={`${rubric.label} · bobot ${rubric.weight}%`} required hint={`Nilai 0–${rubric.maximum}.`}><input id={`score-${rubric.id}`} type="number" min={0} max={rubric.maximum} step="any" value={review.scores[rubric.id] ?? ''} onChange={event => { const scores = { ...review.scores }; if (!event.target.value) delete scores[rubric.id]; else scores[rubric.id] = Number(event.target.value); setReview(current => ({ ...current, scores })); setDirty(true) }} /></Field>)}</div><p role="status">Skor berbobot: {policy.rubric.reduce((sum, r) => sum + (review.scores[r.id] ?? 0) / r.maximum * r.weight, 0).toLocaleString('id-ID', { maximumFractionDigits: 2 })} / 100. Tidak menghasilkan keputusan otomatis.</p><Field id="activity-review-comment" label="Komentar pemeriksaan" required><textarea id="activity-review-comment" rows={4} maxLength={5000} value={review.comment} onChange={event => { setReview(current => ({ ...current, comment: event.target.value })); setDirty(true) }} /></Field><Field id="activity-review-recommendation" label="Rekomendasi" required><select id="activity-review-recommendation" value={review.recommendation} onChange={event => { setReview(current => ({ ...current, recommendation: event.target.value as ActivityReview['recommendation'] })); setDirty(true) }}><option value="">Pilih rekomendasi</option><option value="CONTINUE">Dapat diteruskan</option><option value="REVISION">Perlu revisi</option><option value="REJECT">Tidak direkomendasikan</option></select></Field><div className="form-actions"><Button type="button" variant="outline" onClick={() => persist('REVIEW_DRAFT')}>{actionLabels.REVIEW_DRAFT}</Button><Button type="submit">{actionLabels.REVIEW_FINISH}</Button></div></form> : <p className="info-notice">Penilaian belum dapat diisi sampai SOP/rubrik dan salinan pengajuan tersedia.</p>}</section>}
      {user.role === 'LPPM' && ['REVIEW_COMPLETED', 'PROGRESS_SUBMITTED', 'FINAL_SUBMITTED', 'OUTPUT_PENDING'].includes(activity.status) && <section className="form-section"><h3>Keputusan Ka. LPPM</h3><p className="muted">{complete ? 'Semua pemeriksaan versi aktif selesai.' : 'Menunggu seluruh pemeriksaan versi aktif dan SOP terbit.'}</p>{activity.status === 'REVIEW_COMPLETED' && <><Field id="activity-decision" label="Keputusan proposal"><select id="activity-decision" value={decision} onChange={event => { setDecision(event.target.value as typeof decision); setDirty(true) }}><option value="APPROVE">Setujui</option><option value="REJECT">Tolak</option><option value="REVISION">Minta revisi</option></select></Field>{decision === 'APPROVE' && <Field id="approved-amount" label="Dana disetujui (Rp)" required hint={`Pagu SOP: ${moneyLabel(policy ? Number(policy.profile.budgetCap) : null)}. Maksimal dua desimal.`}><input id="approved-amount" inputMode="decimal" value={amount} onChange={event => { setAmount(event.target.value); setDirty(true) }} /></Field>}</>}<Field id="activity-decision-reason" label="Alasan keputusan" required><textarea id="activity-decision-reason" rows={3} maxLength={5000} value={note} onChange={event => { setNote(event.target.value); setDirty(true) }} /></Field><Button disabled={!complete || (activity.status !== 'REVIEW_COMPLETED' && !policy?.allowMilestones)} onClick={() => request(activity.status === 'REVIEW_COMPLETED' ? decision : 'ACCEPT_MILESTONE')}>{activity.status === 'REVIEW_COMPLETED' ? actionLabels[decision] : actionLabels.ACCEPT_MILESTONE}</Button></section>}
    </fieldset>{error && <p role="alert" className="form-error">{error}</p>}
    <section className="form-section"><h3>Penugasan & Hasil Pemeriksaan</h3>{activity.reviewerIds.length ? <ul>{activity.reviewerIds.map(id => <li key={id}>{config.accounts.find(account => account.id === id)?.name ?? id} · {activity.reviews.some(r => r.reviewerId === id && r.stage === stage && r.submissionVersion === version) ? 'Pemeriksaan versi aktif selesai' : 'Belum selesai'}</li>)}</ul> : <p className="muted">Belum ada reviewer ditugaskan pada tahap ini.</p>}{[...activity.reviews].filter(r => canReadActivityStage(activity, user, r.stage, r.submissionVersion)).reverse().map((entry, index) => <details className="submission-version" key={index}><summary>{entry.actor} · {entry.stage} v{entry.submissionVersion} · {dateLabel(entry.at, true)}</summary><p className="summary-text">{entry.comment}</p><p>Rekomendasi: {{ '': 'Belum ada', CONTINUE: 'Dapat diteruskan', REVISION: 'Perlu revisi', REJECT: 'Tidak direkomendasikan' }[entry.recommendation]}</p><ul>{Object.entries(entry.scores).map(([key, score]) => <li key={key}>{config.policies.find(p => p.id === entry.policyId)?.rubric.find(r => r.id === key)?.label ?? key}: {score}</li>)}</ul></details>)}</section>
    {activity.externalUpdates.length > 0 && user.role !== 'REVIEWER' && <section className="form-section"><h3>Riwayat Status Eksternal</h3>{[...activity.externalUpdates].reverse().map((entry, index) => <details className="submission-version" key={index}><summary>{entry.status} · {dateLabel(entry.evidenceDate)} · dicatat {entry.actor}</summary><p>Sumber: EXTERNAL_MANUAL · {entry.funded ? 'Hibah diterima berdasarkan bukti' : 'Status dilaporkan'}</p>{entry.url && <a className="reference-link" href={entry.url} target="_blank" rel="noreferrer">Buka Sumber Bukti</a>}<FileList files={entry.files} /></details>)}</section>}
    <Dialog open={!!confirm} onOpenChange={open => { if (!busy && !open) setConfirm(null) }} title={confirm ? `${actionLabels[confirm]}?` : 'Konfirmasi'} description="Perubahan status, versi, aktor, dan alasan akan dicatat. Keputusan ini merupakan simulasi lokal."><div className="dialog-actions"><Button variant="outline" disabled={busy} onClick={() => setConfirm(null)}>Periksa kembali</Button><Button disabled={busy} onClick={() => confirm && persist(confirm)}>{busy ? 'Menyimpan…' : 'Simpan Simulasi'}</Button></div></Dialog>
  </div>
}
